---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: SPINNAKER_NAMESPACE
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: example/minio/minio:latest
        imagePullPolicy: IfNotPresent
        args:
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:  
              name: minio
              key: username
        - name: MINIO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: minio
              key: password
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: SPINNAKER_NAMESPACE
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: minio
  namespace: SPINNAKER_NAMESPACE 
data:
  username: MINIO_USER
  password: MINIO_PASSWORD

