---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: docker.io/minio/minio:latest
        args:
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:  
              name: minio
              key: username
        - name: MINIO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: minio
              key: password
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: minio
data:
  username: opsmx123456
  password: opsmx123456

